language: generic

dist: bionic

## Uncomment the following lines if you require extra dependencies
#before_install:
# - sudo apt-get install ghostscript # If you use latex > dvips > ps2pdf
# - sudo apt-get install python-pygments # If you use the minted package
  # If you use custom fonts:
# - mkdir $HOME/.fonts
# - cp -a $TRAVIS_BUILD_DIR/src/fonts/. $HOME/.fonts/
# - fc-cache -f -v

install:
  - source ./texlive/texlive-install.sh

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

# Change working directory so including files will work
before_script: 
  - sudo curl -L https://api.github.com/repos/adobe-fonts/source-serif-pro/tarball -o source-serif-pro.tar.gz 
  - sudo curl -L https://api.github.com/repos/adobe-fonts/source-sans-pro/tarball -o source-sans-pro.tar.gz
  - tar -xf source-serif-pro.tar.gz 
  - tar -xf source-sans-pro.tar.gz
  - fc-cache -v adobe-fonts-source-*/
  - cd $TRAVIS_BUILD_DIR/src/
script:
  # Texliveonfly will download packages automatically
  - texliveonfly src/latex/page-layout.tex
  # You can use latexmk to automatically handle bibtex and references (recommended)
  - latexmk -shell-escape -lualatex -pdf src/latex/page-layout.tex

    # Texliveonfly will download packages automatically
  - texliveonfly src/latex/page-layout-with-margin-notes.tex
  # You can use latexmk to automatically handle bibtex and references (recommended)
  - latexmk -shell-escape -lualatex -pdf src/latex/page-layout-with-margin-notes.tex

  # But you could use any other compiler as well instead of latexmk. Example:
#  - pdflatex main.tex
#  - bibtex main
#  - pdflatex main.tex
#  - pdflatex main.tex # Compile twice to fix references

  # You can also pass arguments to texliveonfly:
#  - texliveonfly --arguments='-shell-escape' main.tex

## Uncomment the following lines to see the packages installed in travis
#after_script:
#  - export PATH=/tmp/texlive/bin/x86_64-linux:$PATH
#  - tlmgr list --only-installed | grep -oP 'i \K.+?(?=:)'