= Writing style guide
Gabriel Arazas <foo.dogsquared@gmail.com>
2019-09-23
:toc:

Here's my general style guide for writing for future references. 
As such, this is updated periodically. 

Most of the rules set here are the result of me being lazy and avoiding future migraines. 
It also focuses on future-proofing your content. 

This aims to save time on searching, archiving, and editing your document. 
It also enforces consistency with the target persona. 

This writing style guide is based from multiple sources. 
This is mainly inspired from http://www.cs.uky.edu/~raphael/writing.html[_Hints on writing style_], https://www.writethedocs.org/guide/writing/beginners-guide-to-docs/[_A beginner’s guide to writing documentation_ from "Write the Docs"], https://docs.microsoft.com/en-us/style-guide/welcome/[_Microsoft Writing Style Guide_], and https://www.ox.ac.uk/sites/files/oxford/media_wysiwyg/University%20of%20Oxford%20Style%20Guide.pdf[_University of Oxford Style Guide_]. 




== Write one sentence per line 

There are no character limits per line enforced but be practical with the limit. 
The https://sembr.org/[Semantic Line Breaks] does not apply here since it is too fuzzy. 
Instead, I'll make it one sentence for all types. 

For clarification, sentences that are connected with a semicolon are considered two sentences. 
They need to be in separated lines. 

In writing with https://asciidoctor.org/[Asciidoctor], there are cases where this particular rule will break. 
In case that the sentence is filled with macros (commonly footnotes) then we apply the semantic line breaks here. 




== Document structure 

Regarding the document itself, it should follow the set guidelines below. 

* The document title should be formatted in sentence case (only capitalize the first word). 
Proper nouns should be capitalized correctly. 
* A revision string should be present in all documents. 
This could be the Git commit hash or the modified datestamp in https://www.iso.org/iso-8601-date-and-time-format.html[ISO 8601]. 
* A list of authors. 
* A list of contributors (if the document is open for contributions). 
Since not all documents are applied with Git, the latter is preferred. 
* All types of headers within the document are in sentence case. 
* In case the document will use sectioning numbers, stay with using numbers to easily recognize the hierarchy. 




== Document sections 

There are different kinds and parts of a document. 
Nonetheless, title of chapters, sections, subsections, parts, and the document itself should be written in sentence case. 

For easy reference, there's a following list of parts of a document that should be written in sentence case. 

* The document title. 
* The parts and chapters, if it's a book. 
* The sections and its subsections. 

A document may also have additional sections. 
However, the section should appear if it is necessary and satisfies their related condition(s). 

* The abstract, if it tackles a technical concept. 
* The bibliography, if it contains many references to works. 
* The appendix, if the document is too extensive. 
* Glossaries, if the document is too technical. 
* The conclusion, if it's an article and the like. 




== Raw source spacing 

While the output may be the same, it is still important for the raw source to be readable. 
Hence, there is a need to space out certain parts of a raw document. 

It will also make it easier to read and maintain the document. 

* If possible, main title (`<h1>` or any equivalent) should be in the first line.
* Headers (`<h2>` or any equivalent) should be preceded by four newlines. 
* All types of subheaders (`<h3>`, ..., `<h6>` or any equivalent) should be preceded by two newlines. 
* There should be a newline before the end of the document. 
* Once a list item contains sublists, the entire list should be spaced out. 

A particular rule may be nullified if the raw source spacing with the rule applied does affect the output. 




== General style

* Use simple language even in a technical document. 
* Write in informal tone. 
* Write the content in present tense. 
* Ensure sentences are written https://www.grammarly.com/blog/parallelism/[in parallel]. 
* Avert using double negatives (e.g., "not unusual" and "no different"). 
Phrases such as "not less than" are still accepted if it's used mathematically. 
* Avoid using contractions (e.g., "do not" instead of "don't", "shall not" instead of "shan't"). 
* For introducing abbreviations, write out the full name first then the abbreviation in parenthesis. 
Then you can now use the abbreviated form after. 
* Restrict the number of sentences in each paragraph to have a maximum of 10. 
* Avoid using unit symbols (e.g., `"` for inches, `°` for degrees) in writing. 
* No emojis! >:-D 
* Emoticons are accepted and should be used sparingly. 
* Texting lingo such as IDK (I don't know), BRB (be right back), and LOL (laugh out loud) are heavily prohibited. 
* Use the Latin words "i.e." (that is) and "e.g." (for example) for parenthetical materials. 
Otherwise, use the language equivalent. 
Also add a comma at the end. 



== Common words 

I take note that I usually use certain words a lot. 
To make the writing not monotonous and spice things up a bit, consecutive use of those words are discouraged. 

Just for the sake of quick reference, there is a table of common words with their synonyms. 

[cols="4*",options="header"]
|===
| Common word(s) 
| Type 
| Suggested words 
| Note

| usually, commonly 
| adverb
| normally, frequently, consistently, generally, regularly, routinely 
| 

| variations, variants 
| noun
| versions, branches, alternatives
|

| quick 
| adjective
| fast, agile, rapid, swift, immediate 
| 

| common 
| adjective 
| typical, universal, ubiquitous, usual, everyday 
| 

| run
| verb 
| invoke, call 
| This is used to mean running a command (e.g., from the shell) or invoking a function (e.g., from source code). 
Pedantic meaning of each term is not considered yet. 

|===




== Figurative language 

* Most importantly, make sure your point works without the use of figurative language. 
* Use of hyperboles, understatements, similes, and clichés are discouraged. 
* Use very minimal amount of colloqualisms and slang. 
* Use minimal amount of metaphors and analogies. 
* An argument/point can only have a metaphor or an analogy but not both. 
* Don't build your whole (or even majority) of your point around metaphors and analogies. If you did, reconsider your argument. 




== Text formatting

* Use boldface only for emphasizing. 
* Use italics for referring to a title of a work such as the title of an article, book, audio, or video. 
* Avoid using underlines, strikethroughs, and all caps. 
* Typeblock elements (e.g., paragraphs, images, and equations) should be spaced out in the raw source. 




== Numbers 

* Spell out the numbers 0 to 9. 
If you have multiple numbers in the same sentence, you can use the figures instead. 
* As a consequence of the above rule, negative numbers should always be rendered in figures (e.g., -1 instead of negative one). 
* Use appropriate units for the numbers. 
* The same applies for ordinal numbers. 
Spell out 1st to 10th unless you have multiple ordinals. 
* Don't use superscript for ordinal numbers. 




== Date and time 

* Strictly write with 24-hour clock format (e.g., 10:23, 22:41) for the time. 
* In ranking of importance, the year has the highest priority. 
In other words, any date or datetime strings can be trimmed down to only its year and it still gives a context to it. 
* As a consequence of the previous rule, a year should be present at all times (e.g., "July 2015" instead of "July"). 
* Use https://www.iso.org/iso-8601-date-and-time-format.html[ISO 8601] to refer to dates and datetime. 
* Avoid using relative dates (e.g., as of this writing, two weeks ago). 
Instead, be explicit (e.g., as of 2019-10-01, starting from 2019-09-16). 




== Lists

* For ordered lists, avoid using roman numerals and letters. 
Only use numbers similarly to sectioning numbers for hierarchy. 
* If a list is introduced as if it's a part of the sentence, punctuate the list items and the connecting sentence correctly. 
Otherwise, start with each list item as if it's another paragraph. 
* Use https://www.grammarly.com/blog/what-is-the-oxford-comma-and-why-do-people-care-so-much-about-it/[serial commas]. 
* Once a list item contains sublists, the entire list should be spaced out in raw source. 
* Avoid using nested lists two levels deep. 




== References 

* For referring to articles, books, videos, audio, and images, the title should be written exactly as they are. 
If the title is stylized (written all uppercase or lowercase, for example), format it in sentence case. 
* Titles should be italicized. 
If it's not possible, enclose them in quotation marks. 
* If you include the author, enclose them in quotation marks. 
* If you want to cite a source similarly to academic writings, use the https://www.bibme.org/citation-guide/apa/[APA citation style]. 
* For bibliography or reference list, use https://www.bibme.org/citation-guide/apa/[APA style] for citations. 
